KS 2-4 calculate additional materials under buff
NickSigoff/KotlinSprint pull request #12
Opened 2024-05-02 13:51 UTC by NickSigoff

2024-05-03 15:27 UTC, ievetrovdev requested changes

2024-05-03 15:27 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/lesson_2_task_4.kt.kt
> +    val buffRatio = 0.2
В ТЗ фигурирует значение 20 (процентов). Его также надо проинициализировать и только потом производить арифметические операции. Это позволит сделать более гибким и легко изменяемым, если понадобится изменить характеристики.

2024-05-03 20:18 UTC, NickSigoff commented on src/main/kotlin/lesson_2/lesson_2_task_4.kt.kt
> +    val buffRatio = 0.2
Да, согласен. Перепишу под исходные данные

2024-05-04 05:59 UTC, ievetrovdev approved these changes
Отлично

2024-05-04 19:39 UTC, merged