KS 3-2 create and print person data
NickSigoff/KotlinSprint pull request #16
Opened 2024-05-02 19:36 UTC by NickSigoff

2024-05-04 04:23 UTC, ievetrovdev requested changes

2024-05-04 04:23 UTC, ievetrovdev commented on src/main/kotlin/lesson_3/lesson_3_task_2.kt
> +    var personName = "Татьяна"
все супер, только все переменные, которые по коду не изменяются принято делать val

2024-05-04 08:21 UTC, NickSigoff commented on src/main/kotlin/lesson_3/lesson_3_task_2.kt
> +    var personName = "Татьяна"
Поправлю) Отталкивался от другой логики, типа все переменные могут поменяться, но в нашем случае мы меняем только две, а так для изменения доступны все

2024-05-05 06:24 UTC, ievetrovdev approved these changes

2024-05-06 19:41 UTC, merged