KS 5-3 lottery app
NickSigoff/KotlinSprint pull request #26
Opened 2024-05-04 22:24 UTC by NickSigoff

2024-05-07 14:23 UTC, ievetrovdev requested changes

2024-05-07 14:23 UTC, ievetrovdev commented on src/main/kotlin/lesson_5/lesson_5_task_3.kt
> +    } else if ((userFirstNumber == firstWinNumber || userFirstNumber == secondWinNumber) || (userSecondNumber == firstWinNumber || userSecondNumber == secondWinNumber)) {
при использовании || дополнительные скобочки не нужны

2024-05-07 14:23 UTC, ievetrovdev commented on src/main/kotlin/lesson_5/lesson_5_task_3.kt
> +    if ((userFirstNumber == firstWinNumber || userFirstNumber == secondWinNumber) && (userSecondNumber == firstWinNumber || userSecondNumber == secondWinNumber)) {
Слишком длинная строка (больше 120 символов), как правило в крупных и средних компаниях есть системы проверяющие код, которые не пропустят такое форматирование (например [Detekt](https://detekt.dev/docs/rules/formatting/#maximumlinelength)). Давай добавим переносы

2024-05-07 19:27 UTC, NickSigoff commented on src/main/kotlin/lesson_5/lesson_5_task_3.kt
> +    } else if ((userFirstNumber == firstWinNumber || userFirstNumber == secondWinNumber) || (userSecondNumber == firstWinNumber || userSecondNumber == secondWinNumber)) {
Да, не нужны, просто заключил в скобки части выражения для читаемости

2024-05-08 07:13 UTC, ievetrovdev commented on src/main/kotlin/lesson_5/lesson_5_task_3.kt
> +    } else if ((userFirstNumber == firstWinNumber || userFirstNumber == secondWinNumber) || (userSecondNumber == firstWinNumber || userSecondNumber == secondWinNumber)) {
Да верно, блоки можно и следует выделять, но все выражение помещать в скобочки излишне

2024-05-08 07:14 UTC, ievetrovdev approved these changes

2024-05-08 07:51 UTC, merged